#!/bin/sh

TCS_LIB_DIR=$1

cp autopilot/target/auto_pilot-1.0.2.jar $TCS_LIB_DIR/auto_pilot/1.0.2/auto_pilot.jar
cp base_exception/target/base_exception-2.0.0.jar $TCS_LIB_DIR/base_exception/2.0.0/base_exception.jar
cp class_associations/target/class_associations-1.0.0.jar $TCS_LIB_DIR/class_associations/1.0.0/class_associations.jar
cp compression_utility/target/compression_utility-2.0.2.jar $TCS_LIB_DIR/compression_utility/2.0.2/compression_utility.jar
cp heartbeat/target/heartbeat-1.0.0.jar $TCS_LIB_DIR/heartbeat/1.0.0/heartbeat.jar
cp review_data_structure/target/review_data_structure-1.0.2.jar $TCS_LIB_DIR/review_data_structure/1.0.2/review_data_structure.jar
cp scorecard_data_structure/target/scorecard_data_structure-1.0.0.jar $TCS_LIB_DIR/scorecard_data_structure/1.0.0/scorecard_data_structure.jar
cp weighted_calculator/target/weighted_calculator-1.0.0.jar $TCS_LIB_DIR/weighted_calculator/1.0.0/weighted_calculator.jar
cp memory_usage/target/memory_usage-2.0.0.jar $TCS_LIB_DIR/memory_usage/2.0.0/memory_usage.jar
cp simple_cache/target/simple_cache-2.0.2.jar $TCS_LIB_DIR/simple_cache/2.0.2/simple_cache.jar
cp authentication_factory/target/authentication_factory-2.0.1.jar $TCS_LIB_DIR/authentication_factory/2.0.1/authentication_factory.jar
cp contest_eligibility_persistence/target/contest_eligibility_persistence-1.0.1.jar $TCS_LIB_DIR/contest_eligibility_persistence/1.0.1/contest_eligibility_persistence.jar
cp contest_eligibility_validation/target/contest_eligibility_validation-1.0.1.jar $TCS_LIB_DIR/contest_eligibility_validation/1.0.1/contest_eligibility_validation.jar
cp deliverable_management/target/deliverable_management-1.2.4.jar $TCS_LIB_DIR/deliverable_management/1.2.4/deliverable_management.jar
cp deliverable_management_persistence/target/deliverable_management_persistence-1.2.7.jar $TCS_LIB_DIR/deliverable_management_persistence/1.2.7/deliverable_management_persistence.jar
cp distribution_tool/target/distribution_tool-1.0.1.jar $TCS_LIB_DIR/distribution_tool/1.0.1/distribution_tool.jar
cp file_system_server/target/file_system_server-1.1.1.jar $TCS_LIB_DIR/file_system_server/1.1.1/file_system_server.jar
cp file_upload/target/file_upload-2.0.0.jar $TCS_LIB_DIR/file_upload/2.0/file_upload.jar
cp guid_generator/target/guid_generator-1.0.1.jar $TCS_LIB_DIR/guid_generator/1.0.1/guid_generator.jar
cp ip_server/target/ip_server-2.0.1.jar $TCS_LIB_DIR/ip_server/2.0.1/ip_server.jar
cp jndi_context_utility/target/jndi_context_utility-2.0.0.jar $TCS_LIB_DIR/jndi_context_utility/2.0.0/jndi_context_utility.jar
cp job_processor/target/job_processor-3.0.1.jar $TCS_LIB_DIR/job_processor/3.0.1/job_processor.jar
cp late_deliverables_management/target/late_deliverables_management-1.0.7.jar $TCS_LIB_DIR/late_deliverables_management/1.0.7/late_deliverables_management.jar
cp late_deliverables_tracker/target/late_deliverables_tracker-1.3.3.jar $TCS_LIB_DIR/late_deliverables_tracker/1.3.3/late_deliverables_tracker.jar
cp logging_wrapper/target/logging_wrapper-2.0.0.jar $TCS_LIB_DIR/logging_wrapper/2.0.0/logging_wrapper.jar
cp object_factory_configuration_api_plugin/target/object_factory_configuration_api_plugin-1.1.0.jar $TCS_LIB_DIR/object_factory_configuration_api_plugin/1.1.0/object_factory_configuration_api_plugin.jar
cp online_review_ajax_support/target/online_review_ajax_support-1.1.2.jar $TCS_LIB_DIR/online_review_ajax_support/1.1.2/online_review_ajax_support.jar
cp online_review_deliverables/target/online_review_deliverables-1.1.1.jar $TCS_LIB_DIR/online_review_deliverables/1.1.1/online_review_deliverables.jar
cp online_review_login/target/online_review_login-2.0.0.jar $TCS_LIB_DIR/online_review_login/2.0.0/online_review_login.jar
cp online_review_phases/target/online_review_phases-1.8.6.jar $TCS_LIB_DIR/online_review_phases/1.8.6/online_review_phases.jar
cp online_review_upload_services/target/online_review_upload_services-1.1.3.jar $TCS_LIB_DIR/online_review_upload_services/1.1.3/online_review_upload_services.jar
cp phase_management_persistence/target/phase_management_persistence-1.0.4.jar $TCS_LIB_DIR/phase_management_persistence/1.0.4/phase_management_persistence.jar
cp project_management_persistence/target/project_management_persistence-1.2.4.jar $TCS_LIB_DIR/project_management_persistence/1.2.4/project_management_persistence.jar
cp project_payment_calculator/target/project_payment_calculator-1.1.0.jar $TCS_LIB_DIR/project_payment_calculator/1.1.0/project_payment_calculator.jar
cp project_payment_management/target/project_payment_management-1.0.1.jar $TCS_LIB_DIR/project_payment_management/1.0.1/project_payment_management.jar
cp project_phase_template/target/project_phase_template-1.2.0.jar $TCS_LIB_DIR/project_phase_template/1.2.0/project_phase_template.jar
cp resource_management/target/resource_management-1.1.2.jar $TCS_LIB_DIR/resource_management/1.1.2/resource_management.jar
cp resource_management_persistence/target/resource_management_persistence-1.2.6.jar $TCS_LIB_DIR/resource_management_persistence/1.2.6/resource_management_persistence.jar
cp review_application_management/target/review_application_management-1.0.2.jar $TCS_LIB_DIR/review_application_management/1.0.2/review_application_management.jar
cp review_assignment/target/review_assignment-1.2.1.jar $TCS_LIB_DIR/review_assignment/1.2.1/review_assignment.jar
cp review_feedback_management/target/review_feedback_management-2.0.1.jar $TCS_LIB_DIR/review_feedback_management/2.0.1/review_feedback_management.jar
cp review_management/target/review_management-1.2.1.jar $TCS_LIB_DIR/review_management/1.2.1/review_management.jar
cp review_management_persistence/target/review_management_persistence-1.2.4.jar $TCS_LIB_DIR/review_management_persistence/1.2.4/review_management_persistence.jar
cp review_score_aggregator/target/review_score_aggregator-1.0.1.jar $TCS_LIB_DIR/review_score_aggregator/1.0.1/review_score_aggregator.jar
cp review_score_calculator/target/review_score_calculator-1.0.4.jar $TCS_LIB_DIR/review_score_calculator/1.0.4/review_score_calculator.jar
cp scorecard_management/target/scorecard_management-1.0.1.jar $TCS_LIB_DIR/scorecard_management/1.0.1/scorecard_management.jar
cp scorecard_management_persistence/target/scorecard_management_persistence-1.0.3.jar $TCS_LIB_DIR/scorecard_management_persistence/1.0.3/scorecard_management_persistence.jar
cp terms_of_use/target/terms_of_use-1.1.0.jar $TCS_LIB_DIR/terms_of_use/1.1.0/terms_of_use.jar
cp user_project_data_store/target/user_project_data_store-1.1.2.jar $TCS_LIB_DIR/user_project_data_store/1.1.2/user_project_data_store.jar
cp topcoder_commons_utility/target/topcoder_commons_utility-1.0.0.jar $TCS_LIB_DIR/topcoder_commons_utility/1.0.0/topcoder_commons_utility.jar
cp command_line_utility/target/command_line_utility-1.0.0.jar $TCS_LIB_DIR/command_line_utility/1.0.0/command_line_utility.jar
cp configuration_manager/target/configuration_manager-2.2.1.jar $TCS_LIB_DIR/configuration_manager/2.2.1/configuration_manager.jar
cp configuration_api/target/configuration_api-1.1.0.jar $TCS_LIB_DIR/configuration_api/1.1.0/configuration_api.jar
cp configuration_persistence/target/configuration_persistence-1.0.2.jar $TCS_LIB_DIR/configuration_persistence/1.0.2/configuration_persistence.jar
cp data_validation/target/data_validation-1.1.1.jar $TCS_LIB_DIR/data_validation/1.1.1/data_validation.jar
cp database_abstraction/target/database_abstraction-2.0.0.jar $TCS_LIB_DIR/database_abstraction/2.0.0/database_abstraction.jar
cp db_connection_factory/target/db_connection_factory-1.1.1.jar $TCS_LIB_DIR/db_connection_factory/1.1.1/db_connection_factory.jar
cp document_generator/target/document_generator-3.1.1.jar $TCS_LIB_DIR/document_generator/3.1.1/document_generator.jar
cp email_engine/target/email_engine-3.2.1.jar $TCS_LIB_DIR/email_engine/3.2.1/email_engine.jar
cp executable_wrapper/target/executable_wrapper-1.0.1.jar $TCS_LIB_DIR/executable_wrapper/1.0.1/executable_wrapper.jar
cp id_generator/target/id_generator-3.0.2.jar $TCS_LIB_DIR/id_generator/3.0.2/id_generator.jar
cp job_scheduling/target/job_scheduling-3.2.1.jar $TCS_LIB_DIR/job_scheduling/3.2.1/job_scheduling.jar
cp ldap_sdk_interface/target/ldap_sdk_interface-1.0.2.jar $TCS_LIB_DIR/ldap_sdk_interface/1.0.2/ldap_sdk_interface.jar
cp object_factory/target/object_factory-2.2.0.jar $TCS_LIB_DIR/object_factory/2.2.0/object_factory.jar
cp object_factory_config_manager_plugin/target/object_factory_config_manager_plugin-1.1.0.jar $TCS_LIB_DIR/object_factory_config_manager_plugin/1.1.0/object_factory_config_manager_plugin.jar
cp object_formatter/target/object_formatter-1.0.0.jar $TCS_LIB_DIR/object_formatter/1.0.0/object_formatter.jar
cp phase_management/target/phase_management-1.1.0.jar $TCS_LIB_DIR/phase_management/1.1.0/phase_management.jar
cp project_management/target/project_management-1.2.4.jar $TCS_LIB_DIR/project_management/1.2.4/project_management.jar
cp project_phases/target/project_phases-2.0.3.jar $TCS_LIB_DIR/project_phases/2.0.3/project_phases.jar
cp search_builder/target/search_builder-1.3.2.jar $TCS_LIB_DIR/search_builder/1.3.2/search_builder.jar
cp type_safe_enum/target/type_safe_enum-1.1.0.jar $TCS_LIB_DIR/typesafe_enum/1.1.0/typesafe_enum.jar
cp workdays/target/workdays-1.1.0.jar $TCS_LIB_DIR/workdays/1.1.0/workdays.jar