
SET TCS_LIB_DIR=%1

copy autopilot\target\auto_pilot-1.0.2.jar %TCS_LIB_DIR%\auto_pilot\1.0.2\auto_pilot.jar
copy base_exception\target\base_exception-2.0.0.jar %TCS_LIB_DIR%\base_exception\2.0.0\base_exception.jar
copy class_associations\target\class_associations-1.0.0.jar %TCS_LIB_DIR%\class_associations\1.0.0\class_associations.jar
copy compression_utility\target\compression_utility-2.0.2.jar %TCS_LIB_DIR%\compression_utility\2.0.2\compression_utility.jar
copy heartbeat\target\heartbeat-1.0.0.jar %TCS_LIB_DIR%\heartbeat\1.0.0\heartbeat.jar
copy review_data_structure\target\review_data_structure-1.0.2.jar %TCS_LIB_DIR%\review_data_structure\1.0.2\review_data_structure.jar
copy scorecard_data_structure\target\scorecard_data_structure-1.0.0.jar %TCS_LIB_DIR%\scorecard_data_structure\1.0.0\scorecard_data_structure.jar
copy weighted_calculator\target\weighted_calculator-1.0.0.jar %TCS_LIB_DIR%\weighted_calculator\1.0.0\weighted_calculator.jar
copy memory_usage\target\memory_usage-2.0.0.jar %TCS_LIB_DIR%\memory_usage\2.0.0\memory_usage.jar
copy simple_cache\target\simple_cache-2.0.2.jar %TCS_LIB_DIR%\simple_cache\2.0.2\simple_cache.jar
copy authentication_factory\target\authentication_factory-2.0.1.jar %TCS_LIB_DIR%\authentication_factory\2.0.1\authentication_factory.jar
copy contest_eligibility_persistence\target\contest_eligibility_persistence-1.0.1.jar %TCS_LIB_DIR%\contest_eligibility_persistence\1.0.1\contest_eligibility_persistence.jar
copy contest_eligibility_validation\target\contest_eligibility_validation-1.0.1.jar %TCS_LIB_DIR%\contest_eligibility_validation\1.0.1\contest_eligibility_validation.jar
copy deliverable_management\target\deliverable_management-1.2.4.jar %TCS_LIB_DIR%\deliverable_management\1.2.4\deliverable_management.jar
copy deliverable_management_persistence\target\deliverable_management_persistence-1.2.7.jar %TCS_LIB_DIR%\deliverable_management_persistence\1.2.7\deliverable_management_persistence.jar
copy distribution_tool\target\distribution_tool-1.0.1.jar %TCS_LIB_DIR%\distribution_tool\1.0.1\distribution_tool.jar
copy file_system_server\target\file_system_server-1.1.1.jar %TCS_LIB_DIR%\file_system_server\1.1.1\file_system_server.jar
copy file_upload\target\file_upload-2.0.0.jar %TCS_LIB_DIR%\file_upload\2.0\file_upload.jar
copy guid_generator\target\guid_generator-1.0.1.jar %TCS_LIB_DIR%\guid_generator\1.0.1\guid_generator.jar
copy ip_server\target\ip_server-2.0.1.jar %TCS_LIB_DIR%\ip_server\2.0.1\ip_server.jar
copy jndi_context_utility\target\jndi_context_utility-2.0.0.jar %TCS_LIB_DIR%\jndi_context_utility\2.0.0\jndi_context_utility.jar
copy job_processor\target\job_processor-3.0.1.jar %TCS_LIB_DIR%\job_processor\3.0.1\job_processor.jar
copy late_deliverables_management\target\late_deliverables_management-1.0.7.jar %TCS_LIB_DIR%\late_deliverables_management\1.0.7\late_deliverables_management.jar
copy late_deliverables_tracker\target\late_deliverables_tracker-1.3.3.jar %TCS_LIB_DIR%\late_deliverables_tracker\1.3.3\late_deliverables_tracker.jar
copy logging_wrapper\target\logging_wrapper-2.0.0.jar %TCS_LIB_DIR%\logging_wrapper\2.0.0\logging_wrapper.jar
copy object_factory_configuration_api_plugin\target\object_factory_configuration_api_plugin-1.1.0.jar %TCS_LIB_DIR%\object_factory_configuration_api_plugin\1.1.0\object_factory_configuration_api_plugin.jar
copy online_review_ajax_support\target\online_review_ajax_support-1.1.2.jar %TCS_LIB_DIR%\online_review_ajax_support\1.1.2\online_review_ajax_support.jar
copy online_review_deliverables\target\online_review_deliverables-1.1.1.jar %TCS_LIB_DIR%\online_review_deliverables\1.1.1\online_review_deliverables.jar
copy online_review_login\target\online_review_login-2.0.0.jar %TCS_LIB_DIR%\online_review_login\2.0.0\online_review_login.jar
copy online_review_phases\target\online_review_phases-1.8.6.jar %TCS_LIB_DIR%\online_review_phases\1.8.6\online_review_phases.jar
copy online_review_upload_services\target\online_review_upload_services-1.1.3.jar %TCS_LIB_DIR%\online_review_upload_services\1.1.3\online_review_upload_services.jar
copy phase_management_persistence\target\phase_management_persistence-1.0.4.jar %TCS_LIB_DIR%\phase_management_persistence\1.0.4\phase_management_persistence.jar
copy project_management_persistence\target\project_management_persistence-1.2.4.jar %TCS_LIB_DIR%\project_management_persistence\1.2.4\project_management_persistence.jar
copy project_payment_calculator\target\project_payment_calculator-1.1.0.jar %TCS_LIB_DIR%\project_payment_calculator\1.1.0\project_payment_calculator.jar
copy project_payment_management\target\project_payment_management-1.0.1.jar %TCS_LIB_DIR%\project_payment_management\1.0.1\project_payment_management.jar
copy project_phase_template\target\project_phase_template-1.2.0.jar %TCS_LIB_DIR%\project_phase_template\1.2.0\project_phase_template.jar
copy resource_management\target\resource_management-1.1.2.jar %TCS_LIB_DIR%\resource_management\1.1.2\resource_management.jar
copy resource_management_persistence\target\resource_management_persistence-1.2.6.jar %TCS_LIB_DIR%\resource_management_persistence\1.2.6\resource_management_persistence.jar
copy review_application_management\target\review_application_management-1.0.2.jar %TCS_LIB_DIR%\review_application_management\1.0.2\review_application_management.jar
copy review_assignment\target\review_assignment-1.2.1.jar %TCS_LIB_DIR%\review_assignment\1.2.1\review_assignment.jar
copy review_feedback_management\target\review_feedback_management-2.0.1.jar %TCS_LIB_DIR%\review_feedback_management\2.0.1\review_feedback_management.jar
copy review_management\target\review_management-1.2.1.jar %TCS_LIB_DIR%\review_management\1.2.1\review_management.jar
copy review_management_persistence\target\review_management_persistence-1.2.4.jar %TCS_LIB_DIR%\review_management_persistence\1.2.4\review_management_persistence.jar
copy review_score_aggregator\target\review_score_aggregator-1.0.1.jar %TCS_LIB_DIR%\review_score_aggregator\1.0.1\review_score_aggregator.jar
copy review_score_calculator\target\review_score_calculator-1.0.4.jar %TCS_LIB_DIR%\review_score_calculator\1.0.4\review_score_calculator.jar
copy scorecard_management\target\scorecard_management-1.0.1.jar %TCS_LIB_DIR%\scorecard_management\1.0.1\scorecard_management.jar
copy scorecard_management_persistence\target\scorecard_management_persistence-1.0.3.jar %TCS_LIB_DIR%\scorecard_management_persistence\1.0.3\scorecard_management_persistence.jar
copy terms_of_use\target\terms_of_use-1.1.0.jar %TCS_LIB_DIR%\terms_of_use\1.1.0\terms_of_use.jar
copy user_project_data_store\target\user_project_data_store-1.1.2.jar %TCS_LIB_DIR%\user_project_data_store\1.1.2\user_project_data_store.jar
copy topcoder_commons_utility\target\topcoder_commons_utility-1.0.0.jar %TCS_LIB_DIR%\topcoder_commons_utility\1.0.0\topcoder_commons_utility.jar
copy command_line_utility\target\command_line_utility-1.0.0.jar %TCS_LIB_DIR%\command_line_utility\1.0.0\command_line_utility.jar
copy configuration_manager\target\configuration_manager-2.2.1.jar %TCS_LIB_DIR%\configuration_manager\2.2.1\configuration_manager.jar
copy configuration_api\target\configuration_api-1.1.0.jar %TCS_LIB_DIR%\configuration_api\1.1.0\configuration_api.jar
copy configuration_persistence\target\configuration_persistence-1.0.2.jar %TCS_LIB_DIR%\configuration_persistence\1.0.2\configuration_persistence.jar
copy data_validation\target\data_validation-1.1.1.jar %TCS_LIB_DIR%\data_validation\1.1.1\data_validation.jar
copy database_abstraction\target\database_abstraction-2.0.0.jar %TCS_LIB_DIR%\database_abstraction\2.0.0\database_abstraction.jar
copy db_connection_factory\target\db_connection_factory-1.1.1.jar %TCS_LIB_DIR%\db_connection_factory\1.1.1\db_connection_factory.jar
copy document_generator\target\document_generator-3.1.1.jar %TCS_LIB_DIR%\document_generator\3.1.1\document_generator.jar
copy email_engine\target\email_engine-3.2.1.jar %TCS_LIB_DIR%\email_engine\3.2.1\email_engine.jar
copy executable_wrapper\target\executable_wrapper-1.0.1.jar %TCS_LIB_DIR%\executable_wrapper\1.0.1\executable_wrapper.jar
copy id_generator\target\id_generator-3.0.2.jar %TCS_LIB_DIR%\id_generator\3.0.2\id_generator.jar
copy job_scheduling\target\job_scheduling-3.2.1.jar %TCS_LIB_DIR%\job_scheduling\3.2.1\job_scheduling.jar
copy ldap_sdk_interface\target\ldap_sdk_interface-1.0.2.jar %TCS_LIB_DIR%\ldap_sdk_interface\1.0.2\ldap_sdk_interface.jar
copy object_factory\target\object_factory-2.2.0.jar %TCS_LIB_DIR%\object_factory\2.2.0\object_factory.jar
copy object_factory_config_manager_plugin\target\object_factory_config_manager_plugin-1.1.0.jar %TCS_LIB_DIR%\object_factory_config_manager_plugin\1.1.0\object_factory_config_manager_plugin.jar
copy object_formatter\target\object_formatter-1.0.0.jar %TCS_LIB_DIR%\object_formatter\1.0.0\object_formatter.jar
copy phase_management\target\phase_management-1.1.0.jar %TCS_LIB_DIR%\phase_management\1.1.0\phase_management.jar
copy project_management\target\project_management-1.2.4.jar %TCS_LIB_DIR%\project_management\1.2.4\project_management.jar
copy project_phases\target\project_phases-2.0.3.jar %TCS_LIB_DIR%\project_phases\2.0.3\project_phases.jar
copy search_builder\target\search_builder-1.3.2.jar %TCS_LIB_DIR%\search_builder\1.3.2\search_builder.jar
copy type_safe_enum\target\type_safe_enum-1.1.0.jar %TCS_LIB_DIR%\typesafe_enum\1.1.0\typesafe_enum.jar
copy workdays\target\workdays-1.1.0.jar %TCS_LIB_DIR%\workdays\1.1.0\workdays.jar